---
- name: Update
  hosts: server
  serial: 1
  gather_facts: true

  tasks:
    - name: Update the package list (Debian)
      ansible.builtin.apt:
        update_cache: true
      when: ansible_distribution == 'Debian'

    - name: Install all packages (Debian)
      ansible.builtin.apt:
        name: "*"
        state: present
      when: ansible_distribution == 'Debian'

    - name: Perform a dist-upgrade (Debian)
      ansible.builtin.apt:
        upgrade: dist
      when: ansible_distribution == 'Debian'

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: true
      when: ansible_distribution == 'Debian'

    - name: Reboot the server
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists